-- CREATE TABLE students(
--  id integer,
--  age integer not null,
--  name_student text
-- )
-- CREATE TABLE teacher_mark(
--     id integer,
--     mark integer not null,
--     teacher text
-- )
-- CREATE TABLE class_faculty(
--     id integer,
--     class text,
--     faculty text
-- -- )
-- INSERT INTO students VALUES (1, 15, 'Panas')
-- INSERT INTO students VALUES (2, 17, 'Katya')
-- INSERT INTO students VALUES (3, 12, 'Den')
-- INSERT INTO students VALUES (4, 20, 'Taras')
-- INSERT INTO students VALUES (5, 18, 'Lina')
-- INSERT INTO students VALUES (6, 19, 'Vanya')
-- INSERT INTO class_faculty VALUES (1, 3, 'Economik')
-- INSERT INTO class_faculty VALUES (2, 5, 'Math')
-- INSERT INTO class_faculty VALUES (3, 10, 'Doctors')
-- INSERT INTO class_faculty VALUES (4, 11, 'Ximicks')
-- INSERT INTO class_faculty VALUES (5, 8, 'Yristyks')
-- INSERT INTO class_faculty VALUES (6, 2, 'Historiks')
-- INSERT INTO teacher_mark VALUES (1, 2, 'Panas')
-- INSERT INTO teacher_mark VALUES (2, 6, 'Katya')
-- INSERT INTO teacher_mark VALUES (3, 10, 'Den')
-- INSERT INTO teacher_mark VALUES (4, 12, 'Taras')
-- INSERT INTO teacher_mark VALUES (5, 7, 'Lina')
-- INSERT INTO teacher_mark VALUES (6, 10, 'Vanya')
